---
# This files is not being templated because there is no use case right now to need a service that points to the super agent (yet)
# I am keeping the file for now although it might not make any sense.
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "newrelic.common.labels" . | nindent 4 }}
  name: {{ include "newrelic.common.naming.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "newrelic.common.labels.selectorLabels" . | nindent 4 }}
